service: basket

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  player:
    handler: basket.handler
    events:
      - httpApi:
          path: /baskets
          method: get
